Require arch to image-tags
Signed-off-by: Joe Elliott <number101010@gmail.com>

diff --git a/tools/image-tag b/tools/image-tag
--- a/tools/image-tag
+++ b/tools/image-tag
@@ -2,9 +2,15 @@
 
 set -o errexit
 set -o nounset
-set -o pipefail
+#set -o pipefail
 
-SHA="$(git rev-parse --short HEAD),latest"
+if [ "$1" = "" ]
+then
+  echo "Usage: $0 architecture postfix required"
+  exit 1
+fi
+
+SHA="$(git rev-parse --short HEAD)-$1,latest-$1"
 
 # If tag, use tag
 TAG=$( (git describe --exact-match 2> /dev/null || echo "") | sed 's/v//g')
@@ -12,5 +18,5 @@ if [ -z "$TAG" ]
 then
       echo ${SHA}
 else
-      echo ${TAG}
+      echo ${TAG}-$1
 fi
